### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by cheeshon** [Magin-CC/technologyPower#1]
安卓5.1 Qpython3L+selenium+chromedriver

**Comment by cheeshon** [comment]
attributeError:TechnologyPower

**Comment by cheeshon** [comment]
What is the resolution of your mobile phone?

**Comment by daydayhappychao** [comment]
我用的是网易mumu安卓模拟器，分辨率是自带的那种

**Comment by cheeshon** [comment]
已经跑起来了，不过你的这个脚本不能脱离电脑，我发现一个更好的基于安卓auto.js的脚本，可以在移动端直接运行https://github.com/miugod/LearningPower，可惜就是作者写的代码对7.0以下系统兼容不好，也找不到提交建议的入口，你能不能看看修改以下适配安卓6.0系统
